#!/bin/sh

set -e

export CFG_FILE_PATH="/config.yaml" \
       CFG_SERVER_ADDR="http://cfgsync:4400" \
       CFG_HOST_IP=$(hostname -i) \
       CFG_HOST_IDENTIFIER="validator-$(hostname -i)" \
       LOG_LEVEL="DEBUG" \
       POL_PROOF_DEV_MODE=true

/usr/bin/logos-blockchain-cfgsync-client

# Download deployment settings generated by cfgsync
curl -sf "${CFG_SERVER_ADDR}/deployment-settings" -o /deployment-settings.yaml

# Force storage_gas_price to 0 so altruistic inscription txs are accepted
sed -i 's/storage_gas_price: [0-9]*/storage_gas_price: 0/' /deployment-settings.yaml

exec /usr/bin/logos-blockchain-node /config.yaml --deployment /deployment-settings.yaml
