#!/bin/sh

set -e

export CFG_FILE_PATH="/config.yaml" \
       CFG_SERVER_ADDR="http://cfgsync:4400" \
       CFG_HOST_IP=$(hostname -i) \
       CFG_HOST_IDENTIFIER="validator-$(hostname -i)" \
       LOG_LEVEL="DEBUG" \
       POL_PROOF_DEV_MODE=true

/usr/bin/logos-blockchain-cfgsync-client

# Download deployment settings generated by cfgsync
curl -sf "${CFG_SERVER_ADDR}/deployment-settings" -o /deployment-settings.yaml

# Single-node test setup: bump slot_activation_coeff from 1/10 to 1/2 so blocks
# (and LIB) advance ~5x faster, keeping the indexer integration test within budget.
# Safe with 1 node since there are no reorgs.
sed -i '/slot_activation_coeff:/{n;n;s/denominator: 10/denominator: 2/}' /deployment-settings.yaml

exec /usr/bin/logos-blockchain-node /config.yaml --deployment /deployment-settings.yaml
